#project_raincoat/docker-compose.dev.yaml
services:
  db:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: raincoat_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rails:
    build:
      context: ./raincoat_api
      dockerfile: Dockerfile.dev
    # command: bundle exec rails server -b 0.0.0.0 -p 3000
    volumes:
      - ./raincoat_api:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/raincoat_development
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  redis_data:
  bundle_cache: