# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Project-specific rules
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'storage/**/*'

# Metrics
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'
    - 'db/**/*'

# Style
Style/Documentation:
  Enabled: false # Optional for API-only apps

Style/StringLiterals:
  EnforcedStyle: single_quotes

# Lint
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
