#raincoat_api/config/database.yaml
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'postgres') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>



development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  database: raincoat_api_development  
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  database: raincoat_api_test
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: raincoat_api_production
    username: raincoat_api
    password: <%= ENV["RAINCOAT_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: raincoat_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: raincoat_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: raincoat_api_production_cable
    migrations_paths: db/cable_migrate
